name: unitypackage

on: 
  workflow_dispatch:
  push:
    tags: [ v* ]

jobs:
  unitypackage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: benjlevesque/short-sha@v2.1
      id: short-sha
      with:
        length: 6

    - uses: actions/checkout@v3
      with:
        repository: Lachee/Unity-Package-Exporter
        path: upe

    - uses: actions/setup-dotnet@v3

    - run: |
        dotnet run -p upe/UnityPackageExporter \
                   -project . \
                   -dir Assets/Plugins/VolumeButtonsPlugin \
                   -output VolumeButtonsPlugin-${{ steps.short-sha.outputs.sha }}.unitypackage

    - uses: actions/upload-artifact@v3
      with:
        path: VolumeButtonsPlugin-${{ steps.short-sha.outputs.sha }}.unitypackage
        name: VolumeButtonsPlugin-${{ steps.short-sha.outputs.sha }}.unitypackage

    - uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: VolumeButtonsPlugin-${{ steps.short-sha.outputs.sha }}.unitypackage
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
