name: unitypackage

on: 
  workflow_dispatch:
  push:
    tags: [ v* ]

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - run: |
        echo "Assets/Plugins.meta" > Plugin.metaList
        find Assets/Plugins -name \*.meta >> Plugin.metaList

    - uses: benjlevesque/short-sha@v1.2
      id: short-sha
      with:
        length: 6

    - uses: pCYSl5EDgo/create-unitypackage@master
      with:
        package-path: VolumeButtonsPlugin-${{ steps.short-sha.outputs.sha }}.unitypackage
        include-files: Plugin.metaList

    - uses: actions/upload-artifact@v2
      with:
        path: VolumeButtonsPlugin-${{ steps.short-sha.outputs.sha }}.unitypackage
        name: VolumeButtonsPlugin-${{ steps.short-sha.outputs.sha }}.unitypackage

    - uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: VolumeButtonsPlugin-${{ steps.short-sha.outputs.sha }}.unitypackage
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}